// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"omnibus-deposit-network/services/payments-svc/internal/biz"
	"omnibus-deposit-network/services/payments-svc/internal/conf"
	"omnibus-deposit-network/services/payments-svc/internal/data"
	"omnibus-deposit-network/services/payments-svc/internal/jobs"
	"omnibus-deposit-network/services/payments-svc/internal/notify"
	"omnibus-deposit-network/services/payments-svc/internal/rails"
	"omnibus-deposit-network/services/payments-svc/internal/sanctions"
	"omnibus-deposit-network/services/payments-svc/internal/server"
	"omnibus-deposit-network/services/payments-svc/internal/service"
)

// Injectors from wire.go:

func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	confServer := provideServerConf(bootstrap)
	authenticator, err := provideAuthenticator(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	confData := provideDataConf(bootstrap)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	notifications := provideNotificationsConf(bootstrap)
	secretBox, err := notify.NewBox(notifications)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repos := data.NewRepos(dataData, secretBox)
	context := provideContext()
	network := provideNetworkConf(bootstrap)
	confSanctions := provideSanctionsConf(bootstrap)
	screener, err := sanctions.New(context, confSanctions, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	bankScreener := provideBankScreener(screener)
	omnibus, cleanup2, err := rails.New(context, network, bankScreener, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	calendar := provideCalendar()
	options, err := provideOptions(bootstrap)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	engine := biz.NewEngine(repos, omnibus, screener, calendar, secretBox, options, logger)
	paymentUseCase := biz.NewPaymentUseCase(engine)
	paymentService := service.NewPaymentService(paymentUseCase)
	accountUseCase := biz.NewAccountUseCase(engine)
	accountService := service.NewAccountService(accountUseCase)
	webhookUseCase := biz.NewWebhookUseCase(engine)
	webhookService := service.NewWebhookService(webhookUseCase)
	complianceUseCase := biz.NewComplianceUseCase(engine)
	treasuryUseCase := biz.NewTreasuryUseCase(engine)
	bankOperationsService := service.NewBankOperationsService(paymentUseCase, complianceUseCase, treasuryUseCase)
	networkUseCase := biz.NewNetworkUseCase(engine)
	networkOperationsService := service.NewNetworkOperationsService(networkUseCase)
	services := server.NewServices(paymentService, accountService, webhookService, bankOperationsService, networkOperationsService)
	httpServer := server.NewHTTPServer(confServer, authenticator, services, dataData, logger)
	grpcServer := server.NewGRPCServer(confServer, authenticator, services, logger)
	processor := biz.NewProcessor(engine)
	webhookRepo := provideWebhookRepo(repos)
	dispatcher := notify.NewDispatcher(webhookRepo, notifications, logger)
	confJobs := provideJobsConf(bootstrap)
	scheduler := jobs.NewScheduler(processor, dispatcher, confJobs, logger)
	app := newApp(logger, httpServer, grpcServer, scheduler)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
